/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "tertiary-fixed": "#ffdad9",
          "on-primary": "#00390e",
          "inverse-surface": "#e1e2e8",
          "surface": "#111418",
          "on-tertiary-container": "#b6032a",
          "tertiary": "#ffe9e8",
          "surface-bright": "#36393e",
          "surface-container": "#1d2024",
          "surface-variant": "#32353a",
          "on-secondary-fixed": "#181c21",
          "inverse-primary": "#006e23",
          "on-error": "#690005",
          "secondary": "#c3c6ce",
          "secondary-fixed-dim": "#c3c6ce",
          "outline-variant": "#3b4b3a",
          "on-tertiary": "#680013",
          "on-secondary-fixed-variant": "#43474d",
          "on-primary-fixed": "#002106",
          "surface-container-high": "#272a2f",
          "on-secondary": "#2d3136",
          "secondary-fixed": "#e0e2ea",
          "background": "#111418",
          "inverse-on-surface": "#2e3135",
          "primary": "#bbffb8",
          "primary-fixed": "#6dff7e",
          "tertiary-container": "#ffc3c2",
          "error-container": "#93000a",
          "surface-container-low": "#191c20",
          "on-error-container": "#ffdad6",
          "surface-container-highest": "#32353a",
          "on-tertiary-fixed": "#410008",
          "on-tertiary-fixed-variant": "#920020",
          "primary-container": "#0df259",
          "on-surface": "#e1e2e8",
          "on-primary-container": "#006921",
          "primary-fixed-dim": "#00e553",
          "on-primary-fixed-variant": "#005318",
          "on-background": "#e1e2e8",
          "surface-tint": "#00e553",
          "surface-dim": "#111418",
          "secondary-container": "#43474d",
          "surface-container-lowest": "#0b0e12",
          "on-surface-variant": "#bacbb5",
          "error": "#ffb4ab",
          "tertiary-fixed-dim": "#ffb3b2",
          "outline": "#849581",
          "on-secondary-container": "#b2b5bc"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Manrope", "sans-serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Manrope", "sans-serif"],
          "manrope": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
